version: "3.9"

services:
  web:
    image: devops-practice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
