name: CI/CD - Build & Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# If your Docker Hub repo is under your personal username, this is correct.
# If it's under an ORG (e.g., myorg/devops-practice), change IMAGE_NAME accordingly:
# IMAGE_NAME: myorg/devops-practice
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice

jobs:
  test:
    name: Build (sanity) on Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Typecheck / Build (fast sanity)
        run: npm run build
        # If you have tests, add:
        # run: |
        #   npm test -- --ci
        #   npm run build

  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
